import json
import time
import httpx
from fastapi import HTTPException
from fastapi.responses import JSONResponse
from typing import AsyncGenerator, Dict, Any, Optional
from config import settings
from core.cache_exact import exact_cache
from core.cache_semantic import semantic_cache

class UpstreamProxy:
    def __init__(self):
        self.client = httpx.AsyncClient(timeout=60.0)

    async def forward_non_streaming(
        self,
        payload: Dict[str, Any],
        headers: Dict[str, str],
        exact_hash: str,
        user_query: str
    ) -> Dict[str, Any]:
        """Forwards request to upstream LLM API and saves response to cache."""
        upstream_key = settings.UPSTREAM_API_KEY or headers.get("authorization", "").replace("Bearer ", "")
        
        # If mock mode explicitly requested
        if upstream_key in ["test", "mock", "none"]:
            mock_resp = self._generate_mock_response(payload)
            if settings.EXACT_CACHE_ENABLED:
                exact_cache.set(exact_hash, payload.get("model", "default"), mock_resp)
            if settings.SEMANTIC_CACHE_ENABLED and user_query:
                semantic_cache.set(user_query, payload.get("model", "default"), mock_resp)
            return mock_resp

        target_url = f"{settings.UPSTREAM_BASE_URL.rstrip('/')}/chat/completions"
        req_headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {upstream_key}"
        }

        resp = await self.client.post(target_url, json=payload, headers=req_headers)
        
        if resp.status_code != 200:
            error_detail = resp.json() if resp.headers.get("content-type", "").startswith("application/json") else {"error": resp.text}
            raise HTTPException(status_code=resp.status_code, detail=error_detail)

        data = resp.json()

        # Cache the successful response
        if settings.EXACT_CACHE_ENABLED:
            exact_cache.set(exact_hash, payload.get("model", "default"), data)
        if settings.SEMANTIC_CACHE_ENABLED and user_query:
            semantic_cache.set(user_query, payload.get("model", "default"), data)

        return data

    async def forward_streaming(
        self,
        payload: Dict[str, Any],
        headers: Dict[str, str],
        exact_hash: str,
        user_query: str
    ) -> AsyncGenerator[str, None]:
        upstream_key = settings.UPSTREAM_API_KEY or headers.get("authorization", "").replace("Bearer ", "")
        
        if upstream_key in ["test", "mock", "none"]:
            # Local mock stream
            full_content = "This is a simulated response generated by Alp-Cost for testing."
            words = full_content.split(" ")
            resp_id = f"chatcmpl-mock-{int(time.time())}"
            model = payload.get("model", "mock-model")

            for word in words:
                chunk = {
                    "id": resp_id,
                    "object": "chat.completion.chunk",
                    "created": int(time.time()),
                    "model": model,
                    "choices": [{
                        "index": 0,
                        "delta": {"content": word + " "},
                        "finish_reason": None
                    }]
                }
                yield f"data: {json.dumps(chunk)}\n\n"
                time.sleep(0.02)

            stop_chunk = {
                "id": resp_id,
                "object": "chat.completion.chunk",
                "created": int(time.time()),
                "model": model,
                "choices": [{
                    "index": 0,
                    "delta": {},
                    "finish_reason": "stop"
                }]
            }
            yield f"data: {json.dumps(stop_chunk)}\n\n"
            yield "data: [DONE]\n\n"

            full_response = self._create_response_obj(resp_id, model, full_content)
            if settings.EXACT_CACHE_ENABLED:
                exact_cache.set(exact_hash, model, full_response)
            if settings.SEMANTIC_CACHE_ENABLED and user_query:
                semantic_cache.set(user_query, model, full_response)
            return

        target_url = f"{settings.UPSTREAM_BASE_URL.rstrip('/')}/chat/completions"
        req_headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {upstream_key}"
        }

        collected_content = []
        model = payload.get("model", "default")
        resp_id = ""

        async with self.client.stream("POST", target_url, json=payload, headers=req_headers) as response:
            if response.status_code != 200:
                err_text = await response.aread()
                yield f"data: {json.dumps({'error': err_text.decode('utf-8')})}\n\n"
                yield "data: [DONE]\n\n"
                return

            async for line in response.aiter_lines():
                if not line:
                    continue
                yield f"{line}\n\n"
                if line.startswith("data: ") and not line.endswith("[DONE]"):
                    try:
                        chunk_json = json.loads(line[6:])
                        resp_id = chunk_json.get("id", resp_id)
                        choices = chunk_json.get("choices", [])
                        if choices:
                            delta = choices[0].get("delta", {})
                            content = delta.get("content", "")
                            if content:
                                collected_content.append(content)
                    except Exception:
                        pass

        full_text = "".join(collected_content)
        if full_text:
            full_response = self._create_response_obj(resp_id, model, full_text)
            if settings.EXACT_CACHE_ENABLED:
                exact_cache.set(exact_hash, model, full_response)
            if settings.SEMANTIC_CACHE_ENABLED and user_query:
                semantic_cache.set(user_query, model, full_response)

    def _generate_mock_response(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        user_query = ""
        for msg in payload.get("messages", []):
            if msg.get("role") == "user":
                user_query = msg.get("content", "")

        return {
            "id": f"chatcmpl-mock-{int(time.time())}",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": payload.get("model", "alp-mock-model"),
            "choices": [{
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": f"The capital of India is New Delhi." if "capital" in user_query.lower() else f"Simulated response to: '{user_query}'"
                },
                "finish_reason": "stop"
            }],
            "usage": {
                "prompt_tokens": len(user_query.split()) * 2,
                "completion_tokens": 15,
                "total_tokens": len(user_query.split()) * 2 + 15
            }
        }

    def _create_response_obj(self, resp_id: str, model: str, content: str) -> Dict[str, Any]:
        return {
            "id": resp_id or f"chatcmpl-{int(time.time())}",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model,
            "choices": [{
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": content
                },
                "finish_reason": "stop"
            }],
            "usage": {
                "prompt_tokens": 20,
                "completion_tokens": len(content.split()),
                "total_tokens": 20 + len(content.split())
            }
        }

proxy = UpstreamProxy()
